import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const interTightItalic = localFont({
  src: "./fonts/InterTight-Italic.ttf",
  variable: "--font-inter-tight-italic",
  // weight: "100 900",
});
const interTight = localFont({
  src: "./fonts/InterTight.ttf",
  variable: "--font-inter-tight",
  // weight: "100 900",
});
const helvetica = localFont({
  src: "./fonts/helvetica_regular.otf",
  variable: "--font-helvetica",
  // weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} ${interTightItalic.variable} ${helvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
